/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTalkingVideoRouteImport } from './routes/api/talking-video'
import { Route as ApiAnimefyRouteImport } from './routes/api/animefy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTalkingVideoRoute = ApiTalkingVideoRouteImport.update({
  id: '/api/talking-video',
  path: '/api/talking-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimefyRoute = ApiAnimefyRouteImport.update({
  id: '/api/animefy',
  path: '/api/animefy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/animefy': typeof ApiAnimefyRoute
  '/api/talking-video': typeof ApiTalkingVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/animefy': typeof ApiAnimefyRoute
  '/api/talking-video': typeof ApiTalkingVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/animefy': typeof ApiAnimefyRoute
  '/api/talking-video': typeof ApiTalkingVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/animefy' | '/api/talking-video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/animefy' | '/api/talking-video'
  id: '__root__' | '/' | '/api/animefy' | '/api/talking-video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnimefyRoute: typeof ApiAnimefyRoute
  ApiTalkingVideoRoute: typeof ApiTalkingVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/talking-video': {
      id: '/api/talking-video'
      path: '/api/talking-video'
      fullPath: '/api/talking-video'
      preLoaderRoute: typeof ApiTalkingVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/animefy': {
      id: '/api/animefy'
      path: '/api/animefy'
      fullPath: '/api/animefy'
      preLoaderRoute: typeof ApiAnimefyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnimefyRoute: ApiAnimefyRoute,
  ApiTalkingVideoRoute: ApiTalkingVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
